test:
  primary:
    adapter: sqlite3
    database: tmp/primary.sqlite3
  cars:
    adapter: sqlite3
    database: tmp/cars.sqlite3
  cars_replica:
    adapter: sqlite3
    database: tmp/cars.sqlite3
    replica: true
