# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

# develop against the core gem in this repo
gem 'dynamic-active-model', path: '..'

group :development, :test do
  gem 'rake'
  gem 'rspec'
  gem 'simplecov', require: false
  gem 'sqlite3'
end
